version: "2.15.1" #We specify a version for Compose. Make sure Compose is compatible with Docker
services:
  client: #Define the client service so we can run it in an isolated environment.
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev #The client service requires a docker file to be specified. For development, weâ€™re going to use the Dockerfile.dev file.
    ports:
      - "3000:3000" #Next, we map the port 5173 to Docker. The React application runs on port 5173, so we need to tell Docker which port to expose for our application.
    volumes:
      - "/app/node_modules"
      - "./:/app"
